function u = auto_u_container(dth,g,l,m1,m2,t,th,x,x_des)
%AUTO_U_CONTAINER
%    U = AUTO_U_CONTAINER(DTH,G,L,M1,M2,T,TH,X,X_DES)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Apr-2023 16:24:57

t2 = cos(th);
t3 = sin(th);
t4 = t2.^2;
u = -(l.*(m1+m2-m2.*t4).*(dth.*(-1.0./1.0e+1)-th.*(5.0./2.0)+x./4.0e+2-x_des./4.0e+2+(x.*5.62949953421312e+14-x_des.*5.62949953421312e+14+7.623746554457959e+15)./(t.*2.251799813685248e+16-5.947003457620718e+18)+(g.*t3.*(m1+m2))./(l.*(m1+m2.*t3.^2))+(dth.^2.*m2.*t2.*t3.*2.0)./(m1.*2.0+m2-m2.*(t4.*2.0-1.0))))./t2;
