function u = auto_u_container(dth,g,l,m1,m2,t,th,x,x_des)
%AUTO_U_CONTAINER
%    U = AUTO_U_CONTAINER(DTH,G,L,M1,M2,T,TH,X,X_DES)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Apr-2023 14:15:48

t2 = cos(th);
t3 = sin(th);
t4 = t2.^2;
u = (l.*(m1+m2-m2.*t4).*(dth./2.0+th.*3.0e+1-x.*(3.0./2.0)+x_des.*(3.0./2.0)+((x.*(-1.0./1.0e+1)+x_des./1.0e+1+4.753202551633695e-3).*3.0e+1)./(t-1.0e+1)-(g.*t3.*(m1+m2))./(l.*(m1+m2.*t3.^2))-(dth.^2.*m2.*t2.*t3.*2.0)./(m1.*2.0+m2-m2.*(t4.*2.0-1.0))))./t2;
