function u = auto_u_simple(dth,dx,g,l,m1,m2,th,x,x_des)
%AUTO_U_SIMPLE
%    U = AUTO_U_SIMPLE(DTH,DX,G,L,M1,M2,TH,X,X_DES)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Apr-2023 22:29:06

t2 = cos(th);
t3 = t2.^2;
u = dx.*m1.*(-1.0./1.0e+2)-(dx.*m2)./1.0e+2-(m1.*x)./1.0e+2-(m2.*x)./1.0e+2+(m1.*x_des)./1.0e+2+(m2.*x_des)./1.0e+2-(g.*m2.*sin(th.*2.0))./2.0+(dx.*m2.*t3)./1.0e+2+(m2.*t3.*x)./1.0e+2-(m2.*t3.*x_des)./1.0e+2-dth.^2.*l.*m2.*sin(th);
