function p2 = auto_p2(l,th,x)
%AUTO_P2
%    P2 = AUTO_P2(L,TH,X)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Apr-2023 14:15:48

p2 = [x+l.*sin(th);-l.*cos(th)];
