function D = auto_D(l,m1,m2,th)
%auto_D
%    D = auto_D(L,M1,M2,TH)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Apr-2023 12:46:49

t2 = cos(th);
t3 = l.*m2.*t2;
D = reshape([m1+m2,t3,t3,l.^2.*m2],[2,2]);
